name: Example Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f2002865@ds.study.iitm.ac.in
        run: echo "Hello, world! 23f2002865@ds.study.iitm.ac.in"
